### ISSUE TITLE
关于如何使用分类器

### ISSUE THREAD

**Issue by albertyou2** [FrankRouter/product-classification#1]
你好，我目前研究的方向是关于商品分类的
很幸运看到了你的代码。但是没有使用说明，能否写一个简单地使用方法？谢谢！@FrankRouter

**Comment by FrankRouter** [comment]
可以看 makefile。

**Comment by albertyou2** [comment]
@FrankRouter 
我想再请教下，你的分类效果如何？

**Comment by FrankRouter** [comment]
运行会生成 report.txt。人肉检查过一批，基本如测试指标反应。小类效果差些。

**Comment by albertyou2** [comment]
好的谢谢~
